version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: 192.168.0.5  # Replace with the actual IP address of your external database
      DATABASE_PORT: 5432  # Default PostgreSQL port
      DATABASE_NAME: recepty  # The name of your database
      DATABASE_USER: python  # Database user
      DATABASE_PASSWORD: Skytak++102  # Database password

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: recepty
      POSTGRES_USER: python
      POSTGRES_PASSWORD: Skytak++102
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
