version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: 192.168.0.5
      DATABASE_PORT: 5432  # Default PostgreSQL port
      DATABASE_NAME: cookbook
      DATABASE_USER: python
      DATABASE_PASSWORD: Skytak++102