# Generated by Django 4.2.2 on 2024-10-12 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Ingredient Group',
                'verbose_name_plural': 'Ingredient Groups',
            },
        ),
        migrations.AddField(
            model_name='amount',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cookbook_app.ingredientgroup', verbose_name='Group'),
        ),
    ]
