# Generated by Django 4.2.2 on 2024-11-04 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook_app', '0002_ingredientgroup_amount_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cookbook_app.unit', verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='amount',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Value'),
        ),
    ]
